[+] ====== Start training... epoch 1 ======
Traceback (most recent call last):
  File "train_model.py", line 106, in <module>
    eval_every=EVAL_EVERY)
  File "train_model.py", line 60, in model_train
    loss = criterion(bat_pred, bat_label.float())
  File "/Users/jiazhuang01/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/jiazhuang01/anaconda3/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 516, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/Users/jiazhuang01/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 2379, in binary_cross_entropy
    input, target, weight, reduction_enum)
RuntimeError: output with shape [8, 1, 256, 256] doesn't match the broadcast shape [8, 2, 256, 256]
